apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEV3TWpRdwpNekk0TlRGYUZ3MDBNVEV3TWpRd016STROVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDaFd2bHdOSDV2dVBaSmpWbjkwNldPZFk0c1NwZGdaWk1OblVyWDBvRGw1WTFGYnZoSgp1TlhXSk9DbG9EL0hSQjAxRFhoLzQ0MHR0dWJicHl6V1NmaklVeUlIckM4WmZFMHpaUHNJS0tuN1hNUFNNRVVDCmovc09xNGM1Mm1rbWE3NksxcXpYeWxjOVFDWDA4S2c1M040aE14T21icEJlR0J5a0FDKzNmSEtIVkdUTHNnMjEKT0kwb3ZiMklFN0ZmREt5QS9TeEk5bXY1YjRBWXlKb1RFbVc0bmJuMHNsL2E5R2lQR09NdU10aGoxU1JKQmMxMgpEa25ldlQwakd0MVlLbVJzQ0oxUlY2U0VPTXNvcjE5QXZPa3pnZFh2amZWOEQ4NmdqRmR0WG03TmwySm1VZFpjCkJjYzhrZ29lZzJ1aTUzeHE5anlyU0dFUWtmbkpxdC9kNWZZYkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJhMEVuaGlGTVpydkxiR3gzLwpORnY1UnFmWDZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBNk00amJmQzhQYm5XUk9lQ2w3YldZYUtqN0dlCkREUGQ5MGpKZXRsaUFPS0xqejNFeG85MGNlMlA3RW9lenFWdnZzT0NmdGU2QXBkQnZmRzdSdTExZ0xvcE9zUUUKbC9XN2toUTVQRUs1bHlaYnNwK1U0SkNFNHdKMnRVcURMT3BlOWo1SGJPYXJ3K1M4TFNpUy9QRXROdVRyNmVUcgo5Z0lkMVVBTzNJajc4RlE0eEFwRVNOZFJNNWM3cDZiMmYzUUZYQU9NN01XU3lQWHNGMzdIY3dsbmZyM2lFNFNUCmF2Qm1SeTVQazZmZGxaZ2lFb29PSVFUUm1yQXdiS2dvdWplZkhOMzErMjBDM0hZRjZXeWR2OE9BM0kzTHRsMUYKSHFFK2M3K1o1TzNaN21xSzNjZXZaTEV2QUVuaDFNYTV1NlVLQU9vVjF6VWk2SDFDcHlpYWUzR2ZvQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://7180ef3d-c92f-4d7d-99b4-65320e88b65d.k8s.ondigitalocean.com
  name: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119
contexts:
- context:
    cluster: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119
    user: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119-admin
  name: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119
current-context: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-1-21-3-do-0-sgp1-1635046046119-admin
  user:
    token: 535ecb93dcd47026de864332d3d2d11ba34f73cfff246a742edcd1414b887767
